package pt.iscte.paddle.linter.misc;

public enum IssueType {
	FAULTY_ASSIGNMENT,
	SELECTION_MISCONCEPTION,
	EMPTY_SELECTION,
	EMPTY_ALTERNATIVE,
	EMPTY_LOOP,
	DUPLICATE_CODE,
	NESTED_CODE,
	FAULTY_BOOLEAN_CHECK,
	FAULTY_RETURN_BOOLEAN_CHECK,
	MAGIC_NUMBER,
	DUPLICATE_SELECTION_GUARD, 
	FAULTY_METHOD_CALL, 
	DUPLICATE_PROCEDURE_CALL,
	TALTOLOGY, 
	CONTRADICTION,
	USELESS_CODE,
	UNREACHABLE_CODE,
}