package pt.iscte.paddle.codequality.misc;

public enum Category {
	FAULTY_ASSIGNMENT,
	SELECTION_MISCONCEPTION,
	EMPTY_SELECTION,
	EMPTY_ALTERNATIVE,
	EMPTY_LOOP,
	DUPLICATE_CODE,
	DEAD_CODE,
	NESTED_CODE,
	FAULTY_BOOLEAN_CHECK 
}
